//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P3AddNewFunctionalityDotNetCore.Resources.Models.ViewModels {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Order {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Order() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("P3AddNewFunctionalityDotNetCore.Resources.Models.Order", typeof(Order).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ErrorMissingAddress {
            get {
                return ResourceManager.GetString("ErrorMissingAddress", resourceCulture);
            }
        }
        
        internal static string ErrorMissingCity {
            get {
                return ResourceManager.GetString("ErrorMissingCity", resourceCulture);
            }
        }
        
        internal static string ErrorMissingCountry {
            get {
                return ResourceManager.GetString("ErrorMissingCountry", resourceCulture);
            }
        }
        
        internal static string ErrorMissingName {
            get {
                return ResourceManager.GetString("ErrorMissingName", resourceCulture);
            }
        }
        
        internal static string ErrorMissingZipCode {
            get {
                return ResourceManager.GetString("ErrorMissingZipCode", resourceCulture);
            }
        }
    }
}
