//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ressource {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProductService {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductService() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("P3AddNewFunctionalityDotNetCore.Resources.Models.Services.ProductService", typeof(ProductService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string MissingName {
            get {
                return ResourceManager.GetString("MissingName", resourceCulture);
            }
        }
        
        public static string MissingPrice {
            get {
                return ResourceManager.GetString("MissingPrice", resourceCulture);
            }
        }
        
        public static string MissingStock {
            get {
                return ResourceManager.GetString("MissingStock", resourceCulture);
            }
        }
        
        public static string PriceNotANumber {
            get {
                return ResourceManager.GetString("PriceNotANumber", resourceCulture);
            }
        }
        
        public static string PriceNotGreaterThanZero {
            get {
                return ResourceManager.GetString("PriceNotGreaterThanZero", resourceCulture);
            }
        }
        
        public static string StockNotAnInteger {
            get {
                return ResourceManager.GetString("StockNotAnInteger", resourceCulture);
            }
        }
        
        public static string StockNotGreaterThanZero {
            get {
                return ResourceManager.GetString("StockNotGreaterThanZero", resourceCulture);
            }
        }
        
        public static string MissingDescription {
            get {
                return ResourceManager.GetString("MissingDescription", resourceCulture);
            }
        }
        
        public static string MissingDetails {
            get {
                return ResourceManager.GetString("MissingDetails", resourceCulture);
            }
        }
    }
}
